version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          key: v2-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: v2-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"

      - run: yarn build
      - run: yarn lint
      - run: yarn test --coverage
      - run: yarn report-coverage
